version: '2'
services:
   mydbapp:
      image: kopteach/testci20_myweb
      ports:
        - "8888:8888"
      depends_on:
        - db
      container_name: myweb

   db:
      image: kopteach/testci20_db
      volumes:
        - db_data:/var/lib/postgresql/data
      container_name: db

volumes:
   db_data:
